version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:3000'
    volumes:
      - ./prisma:/app/prisma
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db

